[build]
  command = "npm run build"
  publish = "out"

[functions]
  directory = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "https://sam.software/*"
  to = "https://samlalli.com/:splat"
  status = 301
  force = true